function Contactosbpm2mm000008 = Read_Contacts(filename, dataLines)
%IMPORTFILE2 Import data from a text file
%  CONTACTOSBPM2MM000008 = IMPORTFILE2(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the numeric data.
%
%  CONTACTOSBPM2MM000008 = IMPORTFILE2(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  Contactosbpm2mm000008 = importfile2("C:\Users\Patricio\Documents\estudio\Doctorado\Asignaturas\Tambor_Aglomerador\Aerículo_Tamaño\programacion\datos_prueba\Contactos_bpm_2mm_000008.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 22-Apr-2026 10:27:21

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "ParticleIDFrom", "TriangleorParticleIDTo", "AbsoluteNormalForce", "Overlap", "ParticleGroupTo", "ContactType", "BondState"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
Contactosbpm2mm000008 = readtable(filename, opts);

%% Convert to output type
Contactosbpm2mm000008 = table2array(Contactosbpm2mm000008);
end