clc
clear all
close all
format longG


%% User input

'Replace these paths with the folders on your own computer. The script will not work if these paths are wrong, incomplete, or do not contain the required CSV files.';
particles_folder = 'C:\Users\YOUR_USER\Documents\YOUR_FOLDER\Particles'; % Folder containing the particle CSV files exported from Rocky.
contacts_folder = 'C:\Users\YOUR_USER\Documents\YOUR_FOLDER\Contacts'; % Folder containing the contact CSV files exported from Rocky.
output_folder = 'C:\Users\YOUR_USER\Documents\YOUR_FOLDER\Results'; % Folder where the script saves the generated STL files and the Excel post-processing results.


particles_folder = Particles_folder; % Internal variable used by the script.
contacts_folder = Contacts_folder; % Internal variable used by the script.
output_folder = Out_folder; % Internal variable used by the script.

initial_time = 125; % First time step to process.
final_time = 125; % Last time step to process.

particle_file_prefix = 'Particles_bpm'; % Change this prefix so it exactly matches the particle CSV files exported from Rocky before the six-digit time number.
contact_file_prefix = 'Contacts_bpm'; % Change this prefix so it exactly matches the contact CSV files exported from Rocky before the six-digit time number.
output_excel_file = fullfile(output_folder, 'Post_results.xlsx'); % Excel file generated by this script.


%% Read Rocky files
num_steps = final_time - initial_time + 1;
P = cell(1,num_steps);
C = cell(1,num_steps);

for time_step = initial_time:final_time
    step_id = time_step - initial_time + 1;
    particle_file = fullfile(particles_folder, [particle_file_prefix num2str(time_step,'%06d') '.csv']);
    contact_file = fullfile(contacts_folder, [contact_file_prefix num2str(time_step,'%06d') '.csv']);
    if ~isfile(particle_file); error('Particle file not found: %s', particle_file); end
    if ~isfile(contact_file); error('Contact file not found: %s', contact_file); end
    P{step_id} = Read_Particles(particle_file, [2, Inf]);
    C{step_id} = Read_Contacts(contact_file, [2, Inf]);
end

%% Extract particle information and active bonded contacts
bonded_contacts = cell(1,length(P));
particle_x = cell(1,length(P));
particle_y = cell(1,length(P));
particle_z = cell(1,length(P));
particle_diameter = cell(1,length(P));
particle_id = cell(1,length(P));

for step_id = 1:length(P)
    particle_x{step_id} = P{step_id}(:,4);
    particle_y{step_id} = P{step_id}(:,5);
    particle_z{step_id} = P{step_id}(:,6);
    particle_diameter{step_id} = P{step_id}(:,10);
    particle_id{step_id} = P{step_id}(:,2);
    bonded_contact_counter = 0;
    bonded_contacts{step_id} = [];
    for contact_row = 1:size(C{step_id},1)
        % Bond condition. Change this condition only if the exported contact columns are different.
        if C{step_id}(contact_row,8) ~= 0
            bonded_contact_counter = bonded_contact_counter + 1;
            bonded_contacts{step_id}(bonded_contact_counter,:) = C{step_id}(contact_row,:);
        end
    end
end

%% Identify metaparticles from bonded contacts
metaparticle_groups = cell(1,length(P));

for step_id = 1:length(P)
    metaparticle_groups{step_id} = cell(1,size(bonded_contacts{step_id},1));
    counted_ids = [];
    counted_group_index = [];
    group_counter = 0;
    for contact_row = 1:size(bonded_contacts{step_id},1)
        contact_particle_ids = bonded_contacts{step_id}(contact_row,2:3);
        ids_are_counted = ismember(contact_particle_ids, counted_ids);
        if ~any(ids_are_counted)
            group_counter = group_counter + 1;
            metaparticle_groups{step_id}{group_counter} = contact_particle_ids;
            counted_ids = [counted_ids, metaparticle_groups{step_id}{group_counter}];
            counted_group_index = [counted_group_index, group_counter*ones(1,length(metaparticle_groups{step_id}{group_counter}))];
        elseif sum(ids_are_counted) == 1
            counted_id = contact_particle_ids(ids_are_counted);
            new_id = contact_particle_ids(~ids_are_counted);
            target_group = counted_group_index(counted_ids == counted_id);
            target_group = target_group(1);
            metaparticle_groups{step_id}{target_group} = [metaparticle_groups{step_id}{target_group}, new_id];
            counted_ids = [counted_ids, new_id];
            counted_group_index = [counted_group_index, target_group];
        elseif sum(ids_are_counted) == 2
            first_id = contact_particle_ids(1);
            second_id = contact_particle_ids(2);
            first_group = counted_group_index(counted_ids == first_id);
            second_group = counted_group_index(counted_ids == second_id);
            first_group = first_group(1);
            second_group = second_group(1);
            if first_group ~= second_group
                metaparticle_groups{step_id}{first_group} = [metaparticle_groups{step_id}{first_group}, metaparticle_groups{step_id}{second_group}];
                metaparticle_groups{step_id}{second_group} = [];
                counted_group_index(counted_group_index == second_group) = first_group;
            end
        end
    end
    for group_id = 1:group_counter
        metaparticle_groups{step_id}{group_id} = unique(metaparticle_groups{step_id}{group_id});
    end
    metaparticle_groups{step_id} = metaparticle_groups{step_id}(~cellfun(@isempty, metaparticle_groups{step_id}));
end

%% Create particle data for each metaparticle
metaparticle_data = cell(1,length(P));
unbonded_particles = cell(1,length(P));

for step_id = 1:length(P)
    metaparticle_data{step_id} = cell(1,length(metaparticle_groups{step_id}));
    particle_row_ids = P{step_id}(:,1);
    for metaparticle_id = 1:length(metaparticle_groups{step_id})
        group_ids = unique(metaparticle_groups{step_id}{metaparticle_id});
        row_index = ismember(particle_row_ids, group_ids);
        metaparticle_data{step_id}{metaparticle_id} = P{step_id}(row_index,1:10);
    end
    used_ids = [];
    for metaparticle_id = 1:length(metaparticle_data{step_id})
        used_ids = [used_ids; metaparticle_data{step_id}{metaparticle_id}(:,1)];
    end
    used_ids = unique(used_ids);
    unused_index = ~ismember(P{step_id}(:,1), used_ids);
    unbonded_particles{step_id} = P{step_id}(unused_index,:);
end

%% Generate surface points for each bonded metaparticle
n_points = 100; % Number of random surface points generated per sphere.
surface_x = cell(1,length(P));
surface_y = cell(1,length(P));
surface_z = cell(1,length(P));
rotation_matrix = cell(1,length(P));
translated_positions = cell(1,length(P));
new_origin = cell(1,length(P));
particle_positions = cell(1,length(P));
rotated_positions = cell(1,length(P));

for step_id = 1:length(P)
    surface_x{step_id} = cell(1,length(metaparticle_data{step_id}));
    surface_y{step_id} = cell(1,length(metaparticle_data{step_id}));
    surface_z{step_id} = cell(1,length(metaparticle_data{step_id}));
    rotation_matrix{step_id} = cell(1,length(metaparticle_data{step_id}));
    translated_positions{step_id} = cell(1,length(metaparticle_data{step_id}));
    new_origin{step_id} = cell(1,length(metaparticle_data{step_id}));
    particle_positions{step_id} = cell(1,length(metaparticle_data{step_id}));
    rotated_positions{step_id} = cell(1,length(metaparticle_data{step_id}));
    for metaparticle_id = 1:length(metaparticle_data{step_id})
        particle_positions{step_id}{metaparticle_id} = metaparticle_data{step_id}{metaparticle_id}(:,4:6);
        [idx1, idx2, ~] = findFarthestPoints(particle_positions{step_id}{metaparticle_id});
        reference_point = particle_positions{step_id}{metaparticle_id}(idx2,:);
        new_origin{step_id}{metaparticle_id} = particle_positions{step_id}{metaparticle_id}(idx1,:);
        ex = reference_point - new_origin{step_id}{metaparticle_id};
        ex = ex/norm(ex);
        reference_vector = [0, 0, 1];
        if abs(dot(reference_vector, ex)) > 0.9
            reference_vector = [1, 0, 0];
        end
        ez = cross(ex, reference_vector);
        ez = ez/norm(ez);
        ey = cross(ez, ex);
        ey = ey/norm(ey);
        rotation_matrix{step_id}{metaparticle_id} = [ex; ey; ez];
        translated_positions{step_id}{metaparticle_id} = particle_positions{step_id}{metaparticle_id} - new_origin{step_id}{metaparticle_id};
        rotated_positions{step_id}{metaparticle_id} = (rotation_matrix{step_id}{metaparticle_id}*translated_positions{step_id}{metaparticle_id}')';
        surface_x{step_id}{metaparticle_id} = [];
        surface_y{step_id}{metaparticle_id} = [];
        surface_z{step_id}{metaparticle_id} = [];
        for particle_row = 1:size(metaparticle_data{step_id}{metaparticle_id},1)
            radius = metaparticle_data{step_id}{metaparticle_id}(particle_row,10)/2;
            theta = 2*pi*rand(n_points,1);
            phi = acos(2*rand(n_points,1) - 1);
            x = rotated_positions{step_id}{metaparticle_id}(particle_row,1) + radius*sin(phi).*cos(theta);
            y = rotated_positions{step_id}{metaparticle_id}(particle_row,2) + radius*sin(phi).*sin(theta);
            z = rotated_positions{step_id}{metaparticle_id}(particle_row,3) + radius*cos(phi);
            surface_x{step_id}{metaparticle_id} = [surface_x{step_id}{metaparticle_id}; x];
            surface_y{step_id}{metaparticle_id} = [surface_y{step_id}{metaparticle_id}; y];
            surface_z{step_id}{metaparticle_id} = [surface_z{step_id}{metaparticle_id}; z];
        end
    end
end

%% Calculate alpha shapes and metaparticle dimensions
alpha = 10;
hull_indices = cell(1,length(P));
volumes = cell(1,length(P));
surface_points = cell(1,length(P));
shell_points = cell(1,length(P));
alpha_shapes = cell(1,length(P));
median_sizes = cell(1,length(P));
metaparticle_lengths = cell(1,length(P));

for step_id = 1:length(P)
    hull_indices{step_id} = cell(1,length(metaparticle_data{step_id}));
    volumes{step_id} = cell(1,length(metaparticle_data{step_id}));
    surface_points{step_id} = cell(1,length(metaparticle_data{step_id}));
    shell_points{step_id} = cell(1,length(metaparticle_data{step_id}));
    alpha_shapes{step_id} = cell(1,length(metaparticle_data{step_id}));
    median_sizes{step_id} = cell(1,length(metaparticle_data{step_id}));
    metaparticle_lengths{step_id} = cell(1,length(metaparticle_data{step_id}));
    for metaparticle_id = 1:length(metaparticle_data{step_id})
        surface_points{step_id}{metaparticle_id} = [surface_x{step_id}{metaparticle_id} surface_y{step_id}{metaparticle_id} surface_z{step_id}{metaparticle_id}];
        [hull_indices{step_id}{metaparticle_id}, volumes{step_id}{metaparticle_id}] = convhull(surface_points{step_id}{metaparticle_id});
        shell_index = unique(hull_indices{step_id}{metaparticle_id}(:));
        shell_points{step_id}{metaparticle_id} = surface_points{step_id}{metaparticle_id}(shell_index,:);
        alpha_shapes{step_id}{metaparticle_id} = alphaShape(shell_points{step_id}{metaparticle_id}, alpha);
        volumes{step_id}{metaparticle_id} = volume(alpha_shapes{step_id}{metaparticle_id});
        dx = max(surface_points{step_id}{metaparticle_id}(:,1)) - min(surface_points{step_id}{metaparticle_id}(:,1));
        dy = max(surface_points{step_id}{metaparticle_id}(:,2)) - min(surface_points{step_id}{metaparticle_id}(:,2));
        dz = max(surface_points{step_id}{metaparticle_id}(:,3)) - min(surface_points{step_id}{metaparticle_id}(:,3));
        metaparticle_lengths{step_id}{metaparticle_id} = [dx dy dz];
        median_sizes{step_id}{metaparticle_id} = median([dx, dy, dz]);
    end
end

%% Export STL files for bonded metaparticles
for step_id = 1:length(P)
    current_time = initial_time + step_id - 1;
    for metaparticle_id = 1:length(alpha_shapes{step_id})
        [triangles, points] = boundaryFacets(alpha_shapes{step_id}{metaparticle_id});
        stl_file = fullfile(output_folder, sprintf('metaparticle_time%d_id%d_bpm-1.stl', current_time, metaparticle_id));
        stlwrite(triangulation(triangles,points), stl_file);
    end
end

%% Add unbonded particles as single-particle metaparticles
all_metaparticle_data = cell(1,length(P));
final_median_sizes = cell(1,length(P));
metaparticle_centers = cell(1,length(P));
metaparticle_masses = cell(1,length(P));

for step_id = 1:length(P)
    all_metaparticle_data{step_id} = cell(1,length(metaparticle_data{step_id}) + size(unbonded_particles{step_id},1));
    for metaparticle_id = 1:length(metaparticle_data{step_id})
        all_metaparticle_data{step_id}{metaparticle_id} = metaparticle_data{step_id}{metaparticle_id};
        final_median_sizes{step_id}(metaparticle_id) = median_sizes{step_id}{metaparticle_id};
        metaparticle_masses{step_id}(metaparticle_id) = sum(metaparticle_data{step_id}{metaparticle_id}(:,3));
    end
    for particle_row = 1:size(unbonded_particles{step_id},1)
        metaparticle_id = length(metaparticle_data{step_id}) + particle_row;
        all_metaparticle_data{step_id}{metaparticle_id} = unbonded_particles{step_id}(particle_row,:);
        final_median_sizes{step_id}(metaparticle_id) = unbonded_particles{step_id}(particle_row,10);
        metaparticle_lengths{step_id}{metaparticle_id} = [unbonded_particles{step_id}(particle_row,10) unbonded_particles{step_id}(particle_row,10) unbonded_particles{step_id}(particle_row,10)];
        rotation_matrix{step_id}{metaparticle_id} = eye(3);
        metaparticle_masses{step_id}(metaparticle_id) = unbonded_particles{step_id}(particle_row,3);
    end
    metaparticle_centers{step_id} = zeros(length(all_metaparticle_data{step_id}),3);
    for metaparticle_id = 1:length(all_metaparticle_data{step_id})
        metaparticle_centers{step_id}(metaparticle_id,1) = mean(all_metaparticle_data{step_id}{metaparticle_id}(:,4));
        metaparticle_centers{step_id}(metaparticle_id,2) = mean(all_metaparticle_data{step_id}{metaparticle_id}(:,5));
        metaparticle_centers{step_id}(metaparticle_id,3) = mean(all_metaparticle_data{step_id}{metaparticle_id}(:,6));
    end
end

%% Export metaparticle data to Excel
metaparticle_headers = {'particle_id', 'particle_mass', 'particle_x_coordinate', 'particle_y_coordinate', 'particle_z_coordinate', 'particle_x_velocity', 'particle_y_velocity', 'particle_z_velocity', 'particle_size', 'metaparticle_size', 'metaparticle_id', 'metaparticle_x_coordinate', 'metaparticle_y_coordinate', 'metaparticle_z_coordinate', 'metaparticle_local_x_length', 'metaparticle_local_y_length', 'metaparticle_local_z_length', 'rotation_matrix_11', 'rotation_matrix_12', 'rotation_matrix_13', 'rotation_matrix_21', 'rotation_matrix_22', 'rotation_matrix_23', 'rotation_matrix_31', 'rotation_matrix_32', 'rotation_matrix_33'};

for step_id = 1:length(P)
    current_time = initial_time + step_id - 1;
    sheet_name = sprintf('Metaparticles_time%d', current_time);
    total_rows = [];
    for metaparticle_id = 1:length(all_metaparticle_data{step_id})
        metaparticle_particle_ids = all_metaparticle_data{step_id}{metaparticle_id}(:,2);
        if isempty(metaparticle_particle_ids)
            continue
        end
        for particle_index = 1:length(metaparticle_particle_ids)
            current_particle_id = metaparticle_particle_ids(particle_index);
            row_index = find(P{step_id}(:,2) == current_particle_id);
            if ~isempty(row_index)
                particle_row = P{step_id}(row_index(1),2:10);
                row_with_metaparticle = [particle_row, final_median_sizes{step_id}(metaparticle_id), metaparticle_id, metaparticle_centers{step_id}(metaparticle_id,1), metaparticle_centers{step_id}(metaparticle_id,2), metaparticle_centers{step_id}(metaparticle_id,3), metaparticle_lengths{step_id}{metaparticle_id}(1,1), metaparticle_lengths{step_id}{metaparticle_id}(1,2), metaparticle_lengths{step_id}{metaparticle_id}(1,3), rotation_matrix{step_id}{metaparticle_id}(1,1), rotation_matrix{step_id}{metaparticle_id}(1,2), rotation_matrix{step_id}{metaparticle_id}(1,3), rotation_matrix{step_id}{metaparticle_id}(2,1), rotation_matrix{step_id}{metaparticle_id}(2,2), rotation_matrix{step_id}{metaparticle_id}(2,3), rotation_matrix{step_id}{metaparticle_id}(3,1), rotation_matrix{step_id}{metaparticle_id}(3,2), rotation_matrix{step_id}{metaparticle_id}(3,3)];
                total_rows = [total_rows; row_with_metaparticle];
            end
        end
    end
    writecell(metaparticle_headers, output_excel_file, 'Sheet', sheet_name, 'Range', 'A1');
    writematrix(total_rows, output_excel_file, 'Sheet', sheet_name, 'Range', 'A2');
end

disp('All metaparticles were exported correctly.');
