clc
clear all
close all
format longG

%% User input
% Replace this path with the Excel file generated by CMRCA. The script will not work if the path, sheet name, or data range are wrong.
workbook_file = 'C:\Users\YOUR_USER\Documents\YOUR_FOLDER\Results\Post_results.xlsx'; % Excel file generated by CMRCA.
sheet_name = 'Metaparticles_time125'; % Sheet containing the metaparticle results.
data_lines = [2, 3014]; % Rows to read from the Excel file. Use row 2 as the first row if row 1 contains headers.

G = read_xlsx(workbook_file, sheet_name, data_lines);

%% Column definition
% Change these column numbers only if the Excel column order was modified.
metaparticle_id_column = 11; % Column containing the metaparticle ID: 1, 2, 3, ...
particle_mass_column = 2; % Column containing the mass of each subparticle [kg].
metaparticle_size_column = 10; % Column containing the characteristic size of each metaparticle.
size_unit = 'm'; % Use 'm' if the metaparticle size is in meters or 'mm' if it is in millimeters.

%% Extract base data
row_metaparticle_id = G(:,metaparticle_id_column);
row_particle_mass = G(:,particle_mass_column);
valid_rows = isfinite(row_metaparticle_id) & isfinite(row_particle_mass) & row_particle_mass > 0;
row_metaparticle_id = row_metaparticle_id(valid_rows);
row_particle_mass = row_particle_mass(valid_rows);
[metaparticle_id,~,metaparticle_group] = unique(row_metaparticle_id);
metaparticle_mass = accumarray(metaparticle_group, row_particle_mass, [], @sum);

%% Get metaparticle size
row_metaparticle_size = G(valid_rows,metaparticle_size_column);
if strcmpi(size_unit,'m'); row_metaparticle_size_mm = row_metaparticle_size*1000; elseif strcmpi(size_unit,'mm'); row_metaparticle_size_mm = row_metaparticle_size; else; error('size_unit must be either ''m'' or ''mm''.'); end
metaparticle_size_mm = accumarray(metaparticle_group, row_metaparticle_size_mm, [], @mean);

%% Remove invalid metaparticles
valid_metaparticles = isfinite(metaparticle_size_mm) & isfinite(metaparticle_mass) & metaparticle_mass > 0 & metaparticle_size_mm > 0;
metaparticle_id = metaparticle_id(valid_metaparticles);
metaparticle_mass = metaparticle_mass(valid_metaparticles);
metaparticle_size_mm = metaparticle_size_mm(valid_metaparticles);

%% Sort metaparticles by size while keeping the associated mass
[metaparticle_size_mm_sorted, sort_idx] = sort(metaparticle_size_mm, 'ascend');
metaparticle_mass_sorted = metaparticle_mass(sort_idx);

%% Calculate cumulative mass passing percentage
metaparticle_total_mass = sum(metaparticle_mass_sorted);
metaparticle_cumulative_mass = cumsum(metaparticle_mass_sorted);
cumulative_mass_passing_pct = metaparticle_cumulative_mass/metaparticle_total_mass*100;

%% Final vectors for plotting
size_plot_mm = metaparticle_size_mm_sorted;
passing_plot_pct = cumulative_mass_passing_pct;
if isempty(size_plot_mm); error('No valid metaparticles were found. Check the Excel file, sheet name, data range, and column numbers.'); end

%% Plot particle size distribution
figure('Color','w')
hold on
box on
grid on
set(gcf,'Units','centimeters','Position',[5 5 13 9])
semilogx(size_plot_mm, passing_plot_pct, '-', 'Color', 'k', 'LineWidth', 0.9, 'HandleVisibility', 'off')
set(gca, 'FontName', 'Times New Roman', 'FontSize', 11, 'TickLabelInterpreter', 'latex', 'LineWidth', 0.8, 'XMinorGrid', 'on', 'YMinorGrid', 'on')
xlabel('Metaparticle size, $d$ [mm]', 'Interpreter', 'latex', 'FontSize', 12)
ylabel('Cumulative mass passing [\%]', 'Interpreter', 'latex', 'FontSize', 12)
ylim([0 100])
x_min = min(size_plot_mm(size_plot_mm > 0));
x_max = max(size_plot_mm);
xlim([0.8*x_min 1.2*x_max])
set(gca,'LooseInset',max(get(gca,'TightInset'),0.02))
